title: Your GitHub Page
theme: jekyll-theme-cayman

# Navigation Links
navbar:
  - title: "Home"
    url: "/"
  - title: "Research papers/Preprints"
    url: "/Papers"
  - title: "Talks and Conferences"
    url: "/Talks"
